# Numpy functions

In [1]:
import numpy as np

## arange()

In [10]:
#syntax - np.arrange(start, end(exclude), step)
array1 = np.arange(1,11)
print("array1:",array1)
array2 = np.arange(0,51,5)
print("array2:",array2)

array1: [ 1  2  3  4  5  6  7  8  9 10]
array2: [ 0  5 10 15 20 25 30 35 40 45 50]


## linspace()

In [16]:
#syntax - np.linspace(start,end(include),no. of values)
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

## reshape()

In [37]:
#syntax - np.reshape(col,row) 
Array_1D = np.arange(1,13)
print("1D-Array:",Array_1D)


1D-Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [35]:
Array_1D.shape

(12,)

In [49]:
Array_2D = Array_1D.reshape(2,6)

print("2D-Array:\n",Array_2D)
print('Dim:',Array_2D.ndim)


2D-Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Dim: 2


In [51]:
Array_3D = Array_1D.reshape(2,3,2)

print("3D-Array:\n",Array_3D)
print('Dim:',Array_3D.ndim)

3D-Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dim: 3


## ravel()

In [54]:
#convert multdimensional array into 1D array
print('3D-Array:\n',Array_3D)
print('1D-Array:\n',Array_3D.ravel())

3D-Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
1D-Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


## flatten() 

In [56]:
#convert multidensional array into 1D Array
Array_3D.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## transpose() 

In [58]:
#convert rows into columns 
Array_2D.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# Mathematic Operations

In [60]:
array1 = np.arange(1,10).reshape(3,3)
array2 = np.arange(5,14).reshape(3,3)
print("Array1:\n",array1)
print("Array2:\n",array2)

Array1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array2:
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [62]:
# Addition
array1 + array2

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [63]:
np.add(array1,array2)

array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [64]:
# subtraction
array2 - array1

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [66]:
np.subtract(array2,array1)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [71]:
#multiplication
#  multiply element by element
print(array1*array2)
print("using function\n",np.multiply(array1,array2))

[[  5  12  21]
 [ 32  45  60]
 [ 77  96 117]]
using function
 [[  5  12  21]
 [ 32  45  60]
 [ 77  96 117]]


In [73]:
# multiply matrix
print(array1@array2)
print('Using fuction\n',np.dot(array1,array2))

[[ 54  60  66]
 [126 141 156]
 [198 222 246]]
Using fuction
 [[ 54  60  66]
 [126 141 156]
 [198 222 246]]


In [75]:
# Division
array1/array2

array([[0.2       , 0.33333333, 0.42857143],
       [0.5       , 0.55555556, 0.6       ],
       [0.63636364, 0.66666667, 0.69230769]])

In [76]:
np.divide(array1,array2)

array([[0.2       , 0.33333333, 0.42857143],
       [0.5       , 0.55555556, 0.6       ],
       [0.63636364, 0.66666667, 0.69230769]])

In [82]:
# find maximun/min values
#  a) from array
print("max:",array1.max())
print('min:',array1.min())

max: 9
min: 1


In [83]:
#  b) from columns
print("max of columns:",array1.max(axis = 0))
print('min of columns:',array1.min(axis = 0))

max of columns: [7 8 9]
min of columns: [1 2 3]


In [84]:
# from rows
print("max of rows:",array1.max(axis=1))
print('min of rows:',array1.min(axis=1))

max of rows: [3 6 9]
min of rows: [1 4 7]


In [87]:
# sum of elements
print("columns sum:", array1.sum(axis=0))
print('rows sum:', array1.sum(axis=1))
print("array's elements sum:",array1.sum())

columns sum: [12 15 18]
rows sum: [ 6 15 24]
array's elements sum: 45


In [91]:
# average
print('average:',array1.mean())
print('rows average:', array1.mean(axis=1))
print('columns average:', array1.mean(axis=0))

average: 5.0
rows average: [2. 5. 8.]
columns average: [4. 5. 6.]


# Slicing

In [93]:
matrix = np.arange(1,101).reshape(10,10)
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [100]:
# dimension
matrix.ndim

2

In [101]:
# obtained 1st element
matrix[0,0]

1

In [107]:
# obtained 3rd rows elements
matrix[2]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [105]:
# obtained 5th col elements
matrix[:,4:5]

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

In [112]:
# obtained  rows elements of 1st-three row and last 1st-three columns elements
print("matrix",matrix)
matrix[0:3,0:3]

matrix [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [114]:
# find element datatype
matrix.dtype

dtype('int32')

In [113]:
# find itemsize 
matrix.itemsize

4

# Concatination and split

In [119]:
print('array1\n',array1)
print('array2\n',array2)

array1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [126]:
# concatenate along column
print(np.concatenate((array1,array2), axis =0))
np.vstack((array1,array2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [129]:
# concatenate along row
print(np.concatenate((array1,array2), axis =1))
np.hstack((array1,array2))

[[ 1  2  3  5  6  7]
 [ 4  5  6  8  9 10]
 [ 7  8  9 11 12 13]]


array([[ 1,  2,  3,  5,  6,  7],
       [ 4,  5,  6,  8,  9, 10],
       [ 7,  8,  9, 11, 12, 13]])

In [130]:
# split
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
np.split(array1,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [133]:
np.split(array1,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

# random sampling using numpy

In [134]:
import random

In [139]:
# generate array having element values b/w 0 & 1
# syntax np.random.random((shape))
np.random.random((2,3))

array([[0.09939102, 0.71176699, 0.23332574],
       [0.46870625, 0.28935464, 0.66418522]])

In [142]:
# generate array having element values in integers
#  syntax- np.random.randint(start,end_ex.,(shape))
np.random.randint(1,4,(3,3))

array([[3, 3, 2],
       [2, 3, 2],
       [3, 1, 1]])

In [144]:
# suffling
print(array1)
np.random.permutation(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [145]:
np.random.permutation(array1)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [146]:
np.random.permutation(array1)

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [147]:
np.random.permutation(array1)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [148]:
for i in range(10):
    print(np.random.permutation(array1))

[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
[[4 5 6]
 [1 2 3]
 [7 8 9]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [164]:
arr=np.arange(0,10).reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [165]:
random.shuffle(arr)



In [166]:
arr

array([[0, 1],
       [2, 3],
       [2, 3],
       [0, 1],
       [6, 7]])